name: Build Flutter APK

on:
  push:
    branches:
      - main  # Especifica la rama que quieres observar, por ejemplo, 'main'.

jobs:
  build:
    runs-on: ubuntu-latest  # Sistema operativo de la máquina virtual.

    steps:
      # Paso 1: Verifica el repositorio.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Paso 2: Instala Flutter y dependencias.
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'  # Especifica la versión de Flutter.

      # Paso 3: Corre la configuración de la herramienta de Flutter.
      - name: Flutter doctor
        run: flutter doctor

      # Paso 4: Descarga dependencias.
      - name: Get dependencies
        run: flutter pub get

      # Paso 5: Compila el APK de release.
      - name: Build APK
        run: flutter build apk --release

      # Paso 6: Guarda el APK como un artefacto.
      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk